name: dart_quill_delta
description: "A Dart port of quill-js-delta, offering a simple and expressive JSON format for describing rich-text content and its changes."
version: 10.8.3
homepage: https://github.com/FlutterQuill/dart-quill-delta
repository: https://github.com/FlutterQuill/dart-quill-delta
issue_tracker: https://github.com/FlutterQuill/dart-quill-delta/issues
documentation: https://github.com/FlutterQuill/dart-quill-delta

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.0
  diff_match_patch: ^0.4.1
  quiver: ^3.2.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
